package com.example.tastetributes.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.remember
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

enum class Orientation {
    PORTRAIT, LANDSCAPE
}

data class Dimensions(
    val small: Dp,
    val smallMedium: Dp,
    val medium: Dp,
    val mediumLarge: Dp,
    val large: Dp,
    val extraLarge: Dp,
    val one: Dp,
    val two: Dp,
    val three: Dp,
    val four: Dp,
    val eight: Dp,
    val ten: Dp,
    val twelve: Dp,
    val fourteen: Dp,
    val sixteen: Dp,
    val eighteen: Dp,
    val twenty: Dp,
    val twentyTwo: Dp,
    val twentyFour: Dp,
    val twentySix: Dp,
    val twentyEight: Dp,
    val thirty: Dp,
    val thirtyTwo: Dp,
    val thirtyFour: Dp,
    val thirtySix: Dp,
    val thirtyEight: Dp,
    val forty: Dp,
    val fortyTwo: Dp,
    val fortyFour: Dp,
    val fortyEight: Dp
)

val smallDimensions = Dimensions(
    small = 1.dp,
    smallMedium = 2.dp,
    medium = 4.dp,
    mediumLarge = 6.dp,
    large = 8.dp,
    extraLarge = 16.dp,
    one = 1.dp,
    two = 2.dp,
    three = 3.dp,
    four = 4.dp,
    eight = 8.dp,
    ten = 10.dp,
    twelve = 12.dp,
    fourteen = 14.dp,
    sixteen = 16.dp,
    eighteen = 18.dp,
    twenty = 20.dp,
    twentyTwo = 22.dp,
    twentyFour = 24.dp,
    twentySix = 26.dp,
    twentyEight = 28.dp,
    thirty = 30.dp,
    thirtyTwo = 32.dp,
    thirtyFour = 34.dp,
    thirtySix = 36.dp,
    thirtyEight = 38.dp,
    forty = 40.dp,
    fortyFour = 44.dp,
    fortyTwo = 42.dp,
    fortyEight = 48.dp,
)

val compactDimensions = Dimensions(
    small = 2.dp,
    smallMedium = 4.dp,
    medium = 6.dp,
    mediumLarge = 8.dp,
    large = 12.dp,
    extraLarge = 16.dp,
    one = 1.dp,
    two = 2.dp,
    three = 3.dp,
    four = 4.dp,
    eight = 8.dp,
    ten = 10.dp,
    twelve = 12.dp,
    fourteen = 14.dp,
    sixteen = 16.dp,
    eighteen = 18.dp,
    twenty = 20.dp,
    twentyTwo = 22.dp,
    twentyFour = 24.dp,
    twentySix = 26.dp,
    twentyEight = 28.dp,
    thirty = 30.dp,
    thirtyTwo = 32.dp,
    thirtyFour = 34.dp,
    thirtySix = 36.dp,
    thirtyEight = 38.dp,
    forty = 40.dp,
    fortyFour = 44.dp,
    fortyTwo = 42.dp,
    fortyEight = 48.dp,
)

val mediumDimensions = Dimensions(
    small = 4.dp,
    smallMedium = 6.dp,
    medium = 8.dp,
    mediumLarge = 12.dp,
    large = 16.dp,
    extraLarge = 24.dp,
    one = 1.dp,
    two = 2.dp,
    three = 3.dp,
    four = 4.dp,
    eight = 8.dp,
    ten = 10.dp,
    twelve = 12.dp,
    fourteen = 14.dp,
    sixteen = 16.dp,
    eighteen = 18.dp,
    twenty = 20.dp,
    twentyTwo = 22.dp,
    twentyFour = 24.dp,
    twentySix = 26.dp,
    twentyEight = 28.dp,
    thirty = 30.dp,
    thirtyTwo = 32.dp,
    thirtyFour = 34.dp,
    thirtySix = 36.dp,
    thirtyEight = 38.dp,
    forty = 40.dp,
    fortyFour = 44.dp,
    fortyTwo = 42.dp,
    fortyEight = 48.dp,
)

val largeDimensions = Dimensions(
    small = 8.dp,
    smallMedium = 12.dp,
    medium = 16.dp,
    mediumLarge = 24.dp,
    large = 32.dp,
    extraLarge = 48.dp,
    one = 1.dp,
    two = 2.dp,
    three = 3.dp,
    four = 4.dp,
    eight = 8.dp,
    ten = 10.dp,
    twelve = 12.dp,
    fourteen = 14.dp,
    sixteen = 16.dp,
    eighteen = 18.dp,
    twenty = 20.dp,
    twentyTwo = 22.dp,
    twentyFour = 24.dp,
    twentySix = 26.dp,
    twentyEight = 28.dp,
    thirty = 30.dp,
    thirtyTwo = 32.dp,
    thirtyFour = 34.dp,
    thirtySix = 36.dp,
    thirtyEight = 38.dp,
    forty = 40.dp,
    fortyFour = 44.dp,
    fortyTwo = 42.dp,
    fortyEight = 48.dp,
)

val LocalDimensions = compositionLocalOf { smallDimensions }

@Composable
fun ProvideAppUtils(dimensions: Dimensions, content: @Composable () -> Unit) {
    val dimSet = remember { dimensions }
    CompositionLocalProvider(LocalDimensions provides dimSet, content = content)
}